// Output formats for the Merit token build. All output is deterministic
// (no timestamps) so `npm run check` can byte-compare against committed files.
import { primitiveOf } from './tokens.mjs';

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const camel = (parts) => parts
  .map((p) => (p === '2xl' ? 'xxl' : p))
  .map((p, i) => (i === 0 ? p : p[0].toUpperCase() + p.slice(1)))
  .join('');
const px = (dim) => Number(String(dim).replace(/px$/, ''));
const ms = (dur) => Number(String(dur).replace(/ms$/, ''));
const hex8 = (hex) => `0xFF${hex.replace('#', '').toUpperCase()}`;
const num = (n) => (Number.isInteger(n) ? `${n}.0` : String(n));
const onlyFor = (t, platform) => !t.extensions['merit.platforms'] || t.extensions['merit.platforms'].includes(platform);

/** color.* drops the `color` segment: color.text.onPrimary → --merit-text-on-primary */
export const cssVar = (t) => `--merit-${(t.path[0] === 'color' ? t.path.slice(1) : t.path).map(kebab).join('-')}`;
/** Dart member name inside its class: color.text.onPrimary → textOnPrimary */
export const dartName = (t, drop = 1) => camel(t.path.slice(drop));

const isThemed = (t) => t.layer === 'semantic' || (t.layer === 'component' && t.type === 'color');

// ---- CSS -------------------------------------------------------------------
function cssFontFamily(list) {
  const generic = new Set(['system-ui', 'sans-serif', 'serif', 'monospace', 'ui-monospace']);
  return list.map((f) => (generic.has(f) ? f : `'${f}'`)).join(', ');
}

function cssDecls(t, all) {
  const name = cssVar(t);
  if (t.ref && all.get(t.ref).type !== 'typography') return [`${name}: var(${cssVar(all.get(t.ref))});`];
  const v = t.value;
  switch (t.type) {
    case 'color': case 'dimension': case 'duration': case 'number': case 'fontWeight':
      return [`${name}: ${v};`];
    case 'cubicBezier':
      return [`${name}: cubic-bezier(${v.join(', ')});`];
    case 'fontFamily':
      return [`${name}: ${cssFontFamily(v)};`];
    case 'typography': {
      const d = [
        `${name}-family: ${cssFontFamily(v.fontFamily)};`,
        `${name}-size: ${v.fontSize};`,
        `${name}-line-height: ${v.lineHeight};`,
        `${name}-weight: ${v.fontWeight};`,
        `${name}-tracking: ${v.letterSpacing};`,
      ];
      if (t.extensions['merit.textTransform']) d.push(`${name}-transform: ${t.extensions['merit.textTransform']};`);
      if (t.extensions['merit.tabularNums']) d.push(`${name}-numeric: tabular-nums;`);
      return d;
    }
    default:
      throw new Error(`No CSS format for $type "${t.type}" (${t.id})`);
  }
}

const block = (selector, lines) => `${selector} {\n${lines.map((l) => `  ${l}`).join('\n')}\n}\n`;

export function formatCss(themes, version) {
  const light = themes.light;
  const all = [...light.values()].filter((t) => onlyFor(t, 'css'));
  const fixed = all.filter((t) => !isThemed(t));
  const semantic = (th) => [...themes[th].values()].filter((t) => t.layer === 'semantic');
  const componentColors = all.filter((t) => t.layer === 'component' && t.type === 'color');
  const offsets = all.filter((t) => t.path[0] === 'shadowOffset');

  const shadowLines = offsets.map((t) => {
    const o = `var(${cssVar(t)})`;
    return `--merit-shadow-${t.path[1]}: ${o} ${o} 0 0 var(--merit-shadow-color);`;
  });

  return [
    `/* GENERATED by merit-project-design-system/scripts/build-tokens.mjs — DO NOT EDIT.`,
    ` * Merit design tokens v${version}. Source: tokens/*.tokens.json`,
    ` * Themes: light on :root, dark on .dark / [data-theme="dark"]. */`,
    '',
    '/* Primitives, typography, sizes — theme-independent */',
    block(':root', fixed.flatMap((t) => cssDecls(t, light))),
    '/* Semantic — light */',
    block(':root', semantic('light').flatMap((t) => cssDecls(t, light))),
    '/* Semantic — dark (outline + hard shadow flip to cream) */',
    block('.dark,\n[data-theme="dark"]', semantic('dark').flatMap((t) => cssDecls(t, themes.dark))),
    '/* Derived — re-declared on every theme scope so var() chains re-resolve',
    '   against the scope\'s semantic values (custom properties resolve where declared). */',
    block(':root,\n.dark,\n[data-theme="dark"]', [
      '/* hard shadows — blur is always 0 */',
      ...shadowLines,
      '/* component colours */',
      ...componentColors.flatMap((t) => cssDecls(t, light)),
    ]),
  ].join('\n');
}

// ---- Dart ------------------------------------------------------------------
const cls = (doc, name, members) => [
  `/// ${doc}`,
  `abstract final class ${name} {`,
  ...members.map((m) => `  ${m}`),
  '}',
  '',
];

const FONT_WEIGHT = { 400: 'w400', 500: 'w500', 600: 'w600', 700: 'w700' };

export function formatDart(themes, version) {
  const light = themes.light;
  const all = [...light.values()].filter((t) => onlyFor(t, 'dart'));
  const group = (g) => all.filter((t) => t.path[0] === g);
  const doc = (t) => (t.description ? ` // ${t.description}` : '');
  const flutterFont = (list) => {
    const fam = all.find((t) => t.type === 'fontFamily' && t.value === list);
    return fam?.extensions['merit.flutter'] ?? list[0];
  };

  const palette = all.filter((t) => t.layer === 'primitive' && t.type === 'color');
  const themed = [...light.values()].filter(isThemed)
    .sort((a, b) => (a.layer === b.layer ? 0 : a.layer === 'semantic' ? -1 : 1));
  const themedValue = (th, id) => {
    const t = themes[th].get(id);
    const p = primitiveOf(themes[th], t);
    return p.layer === 'primitive' ? `MeritPalette.${dartName(p)}` : `Color(${hex8(t.value)})`;
  };

  const typeStyles = group('type').map((t) => {
    const v = t.value;
    const size = px(v.fontSize);
    const tracking = Math.round(size * parseFloat(v.letterSpacing) * 100) / 100;
    const props = [
      `fontFamily: '${flutterFont(v.fontFamily)}'`,
      `fontSize: ${num(size)}`,
      `height: ${num(v.lineHeight)}`,
      `fontWeight: FontWeight.${FONT_WEIGHT[v.fontWeight]}`,
      `letterSpacing: ${num(tracking)}`,
    ];
    if (t.extensions['merit.tabularNums']) props.push('fontFeatures: [FontFeature.tabularFigures()]');
    const note = t.extensions['merit.textTransform'] === 'uppercase' ? ' // render UPPERCASE (Latin only)' : '';
    return `static const TextStyle ${dartName(t)} = TextStyle(${props.join(', ')});${note}`;
  });

  const fields = themed.map((t) => dartName(t));
  const shadowGetters = group('shadowOffset').map((t) =>
    `List<BoxShadow> get shadow${t.path[1].toUpperCase()} => [BoxShadow(offset: const Offset(MeritShadowOffset.${t.path[1]}, MeritShadowOffset.${t.path[1]}), color: shadowColor)];`);

  const instance = (th) => [
    `  static const ${th} = MeritSemanticColors(`,
    ...themed.map((t) => `    ${dartName(t)}: ${themedValue(th, t.id)},`),
    '  );',
  ];

  return [
    '// GENERATED by merit-project-design-system/scripts/build-tokens.mjs — DO NOT EDIT.',
    `// Merit design tokens v${version}. Source: tokens/*.tokens.json`,
    '// Regenerate in the design-system repo, then copy this file verbatim;',
    '// CI (scripts/check-drift.mjs) fails if the copy differs.',
    '',
    "import 'package:flutter/material.dart';",
    '',
    ...cls('Raw palette. Screens should use [MeritSemanticColors] via `context.meritColors`.', 'MeritPalette',
      palette.map((t) => `static const Color ${dartName(t)} = Color(${hex8(t.value)});${doc(t)}`)),
    ...cls('4-pt spacing scale (logical px).', 'MeritSpace',
      group('space').map((t) => `static const double space${t.path[1]} = ${num(px(t.value))};`)),
    ...cls('Corner radii.', 'MeritRadii',
      group('radius').map((t) => `static const double ${dartName(t)} = ${num(px(t.value))};${doc(t)}`)),
    ...cls('Border widths — 2.0 is the signature outline.', 'MeritBorderWidth',
      group('borderWidth').map((t) => `static const double ${dartName(t)} = ${num(px(t.value))};`)),
    ...cls('Hard-shadow offsets (x = y). Blur is ALWAYS 0.', 'MeritShadowOffset',
      group('shadowOffset').map((t) => `static const double ${dartName(t)} = ${num(px(t.value))};${doc(t)}`)),
    ...cls('Durations + curves. Gate non-essential motion on MediaQuery.disableAnimationsOf(context).', 'MeritMotion', [
      ...group('duration').map((t) => `static const Duration ${dartName(t)} = Duration(milliseconds: ${ms(t.value)});${doc(t)}`),
      ...group('easing').map((t) => `static const Cubic ${dartName(t)} = Cubic(${t.value.map(num).join(', ')});`),
    ]),
    ...cls('Opacity levels.', 'MeritOpacity',
      group('opacity').map((t) => `static const double ${dartName(t)} = ${num(t.value)};`)),
    ...cls('Touch targets.', 'MeritTouch',
      group('touch').map((t) => `static const double ${dartName(t)} = ${num(px(t.value))};${doc(t)}`)),
    ...cls('Component sizes.', 'MeritSize',
      group('size').map((t) => `static const double ${dartName(t)} = ${num(px(t.value))};`)),
    ...cls('Bundled font families (pubspec.yaml).', 'MeritFonts',
      group('fontFamily').map((t) => `static const String ${dartName(t)} = '${t.extensions['merit.flutter']}';${doc(t)}`)),
    ...cls('Unified type scale (Latin). SI/TA: letterSpacing 0, height ≥ 1.6 body / 1.3 display.', 'MeritTypeScale', typeStyles),
    '/// Theme-aware semantic + component colours. Register both instances in',
    '/// ThemeData.extensions; read with `context.meritColors`.',
    '@immutable',
    'class MeritSemanticColors extends ThemeExtension<MeritSemanticColors> {',
    '  const MeritSemanticColors({',
    ...fields.map((f) => `    required this.${f},`),
    '  });',
    '',
    ...themed.map((t) => `  final Color ${dartName(t)};${doc(t)}`),
    '',
    ...instance('light'),
    '',
    ...instance('dark'),
    '',
    ...shadowGetters.map((g) => `  ${g}`),
    '',
    '  @override',
    '  MeritSemanticColors copyWith({',
    ...fields.map((f) => `    Color? ${f},`),
    '  }) {',
    '    return MeritSemanticColors(',
    ...fields.map((f) => `      ${f}: ${f} ?? this.${f},`),
    '    );',
    '  }',
    '',
    '  @override',
    '  MeritSemanticColors lerp(MeritSemanticColors? other, double t) {',
    '    if (other == null) return this;',
    '    return MeritSemanticColors(',
    ...fields.map((f) => `      ${f}: Color.lerp(${f}, other.${f}, t)!,`),
    '    );',
    '  }',
    '}',
    '',
    'extension MeritTokensContext on BuildContext {',
    '  /// Semantic colours for the current theme (falls back by brightness',
    '  /// if the extension is not registered yet).',
    '  MeritSemanticColors get meritColors {',
    '    final theme = Theme.of(this);',
    '    return theme.extension<MeritSemanticColors>() ??',
    '        (theme.brightness == Brightness.dark ? MeritSemanticColors.dark : MeritSemanticColors.light);',
    '  }',
    '}',
    '',
  ].join('\n');
}

// ---- JSON ------------------------------------------------------------------
export function formatJson(themes, version) {
  const out = { version, source: 'tokens/*.tokens.json', themes: {} };
  for (const [th, map] of Object.entries(themes)) {
    out.themes[th] = Object.fromEntries([...map.values()].map((t) => [t.id, t.value]));
  }
  return `${JSON.stringify(out, null, 2)}\n`;
}

// ---- SKILL.md generated block ----------------------------------------------
export const SKILL_BEGIN = '<!-- MERIT-TOKENS:BEGIN (generated by scripts/build-tokens.mjs — do not edit by hand) -->';
export const SKILL_END = '<!-- MERIT-TOKENS:END -->';

export function formatSkillBlock(themes, contrastResults, version) {
  const sem = [...themes.light.values()].filter((t) => t.layer === 'semantic');
  const rows = sem.map((t) => {
    const d = themes.dark.get(t.id);
    return `| \`${t.id.replace(/^color\./, '')}\` | \`${t.value}\` | \`${d.value}\` | \`${cssVar(t)}\` | \`context.meritColors.${dartName(t)}\` |`;
  });
  const worst = [...contrastResults].sort((a, b) => a.ratio - b.ratio).slice(0, 5);
  return [
    SKILL_BEGIN,
    `Tokens **v${version}**. Source of truth: \`tokens/*.tokens.json\`; build with \`npm run build\`.`,
    'Outputs: `build/css/merit-tokens.css` (web), `build/dart/merit_tokens.dart` (Flutter),',
    '`build/json/merit-tokens.json`. Never hand-edit outputs or hard-code these hex values.',
    '',
    '### Semantic colours',
    '',
    '| Token | Light | Dark | CSS | Flutter |',
    '|---|---|---|---|---|',
    ...rows,
    '',
    'Component tokens (quiz option states, timer, tier, grade A–F, subject category 1–6, chart 1–5),',
    'spacing (`--merit-space-*` / `MeritSpace`), radii, border widths, hard shadows',
    '(`--merit-shadow-s1…s5` / `context.meritColors.shadowS1…S5`), motion and the type scale',
    '(`--merit-type-*` / `MeritTypeScale`) are in the generated files.',
    '',
    `### Contrast gate — ${contrastResults.length} checks (${contrastResults.length / 2} pairs × light/dark), all ≥ AA`,
    '',
    'Lowest five:',
    '',
    '| Theme | Foreground | Background | Ratio | Min |',
    '|---|---|---|---|---|',
    ...worst.map((r) => `| ${r.theme} | \`${r.fg.replace(/^color\./, '')}\` | \`${r.bg.replace(/^color\./, '')}\` | ${r.ratio.toFixed(2)} | ${r.min} |`),
    SKILL_END,
  ].join('\n');
}
